### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by cap10morgan**
Apparently this is how I entertain myself on my day off.

### CODE REVIEW

**Comment by cap10morgan** [comment]
Hmm... the tests all pass locally. I'll have to look into that CI failure.

**Comment by cap10morgan** [comment]
I guess all it needed was another dependency update!

**Comment by tie-rack** [comment]
@cap10morgan This LGTM now (now that I fixed one lingering problem from updating Korma). Take a look at the change I pushed.

**Comment by cap10morgan** [comment]
Ah, good catch. How did you notice that?

**Pull request merged**
