### PR TITLE
Validate candidate elements

### PR DESCRIPTION
**Pull request by cap10morgan**
@tie-rack I think I have a working BallotName validator here.

(Re-opened against the correct branch)

[Pivotal card](https://www.pivotaltracker.com/story/show/113397267)

### CODE REVIEW

**Comment by tie-rack** [comment]
Oh this is pretty close!

The BallotName element, however, doesn't contain simple text content, but rather [InternationalizedText](https://github.com/votinginfoproject/vip-specification/blob/v5.0-release/vip_spec.xsd#L370-L399). So a one would look like [this](https://github.com/votinginfoproject/vip-specification/blob/v5.0-release/sample_feed.xml#L920-L922):

```xml
    <BallotName>
      <Text language="en">Joseph R. Biden</Text>
    </BallotName>
```

Additionally, the `.0` in the generated paths that you're checking for assume that BallotName elements are always the first child of Candidates.

**Comment by cap10morgan** [comment]
Ah, OK. I'll get that fixed up.

**Comment by cap10morgan** [comment]
This should be ready for review again. I am surprised, though, that build 90646d43521b9ef0d0c85d44f89b9b82026bcdc0 passed. After fixing those tests locally, the build failed (and rightly so). Commit f899353 fixed it.

**Comment by tie-rack** [comment]
Just add `candidate/validate-no-missing-ballot-names` to `vip.data-processor.validation.v5/validations` and this should be good to go!

**Comment by cap10morgan** [comment]
I did that already, I think?

**Comment by tie-rack** [comment]
Sorry, I mean `validate-pre-election-statuses`!

**Comment by tie-rack** [comment]
LGTM!

**Pull request merged**
