### PR TITLE
[CS] Send logs to Loggly (if available)

### PR DESCRIPTION
**Pull request by tie-rack**
* Move to Log4j2 (for proprty substitution in configuration)
* Configure Log4j2 with a syslog appender
* Link a "loggly" container as "syslog" in @.service.template (this will set the required environment variables used in the configuration)

Pivotal story: [102023108](https://www.pivotaltracker.com/story/show/102023108)

### CODE REVIEW

**Comment by cap10morgan** [comment]
Just curious: Why not logback? I was under the impression that "just use logback" was the advice du jour for JVM logging.

**Comment by tie-rack** [comment]
@cap10morgan We were already using Log4j. And the Log4j2 about page throws some shade at Logback: "Log4j 2... provides many of the improvements available in Logback while fixing some inherent problems in Logback's architecture"

In either case, they are both widely used and this was an upgrade, not a lateral move.

**Comment by cap10morgan** [comment]
Gotcha, makes sense. The logging library wars will rage on it seems.

**Comment by bwreid** [comment]
Shiny! So clean. LGTM.

**Pull request merged**
