### PR TITLE
Validate ElectoralDistrict elements

### PR DESCRIPTION
**Pull request by cap10morgan**
Started from the `validate-hours-open` branch so I could use `util/select-path`. But I'm happy to do a new PR if that needs to change. Only commits e2c1fbc and forward are for this feature.

[Pivotal card](https://www.pivotaltracker.com/story/show/114350107)

### CODE REVIEW

**Comment by cap10morgan** [comment]
@tie-rack This should be ready for review now.

**Comment by cap10morgan** [comment]
Once the InternationalizedText PR is merged, I'll apply its approach here.

**Comment by cap10morgan** [comment]
OK this is ready for review again.

**Comment by cap10morgan** [comment]
Shockingly I have found something _else_ I want to change in here before it's reviewed (hint: it's a centralization of the "validate that it's one of these enum values" code along the lines of what I did with the no-missing code recently).

**Comment by cap10morgan** [comment]
Once the approach in #146 for validating enum elements is settled upon and merged, I'd like to apply it to this branch too. That should just involve deleting code because the general DistrictType validator in #146 should replace the type-format validator in here.

**Comment by tie-rack** [comment]
Beautiful

**Pull request merged**
